name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: ${{ github.workspace }}/.cargo
  RUSTFLAGS: -D warnings -A unused-imports
  RUSTDOCFLAGS: -D warnings
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable --no-self-update
      - run: rustc -Vv
      - run: cargo fmt --all -- --check

  unit-tests:
    name: Tests - ${{ matrix.os }} - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          toolchain:
            - stable
          os:
            - ubuntu-latest
            - macos-latest
            # - windows-latest
          include:
            - toolchain: beta
              os: ubuntu-latest
            - toolchain: nightly
              os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/cache@v3.3.2
      with:
        path: |
          ${{ env.CARGO_HOME }}
          target
        key: unit-test-${{ runner.os }}-${{ matrix.toolchain}}
    - name: Install NuGet (windows)
      if: matrix.os == 'windows-latest'
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '5.x'
    - name: Install BLAS (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libblas-dev liblapack-dev libopenblas-dev
    - name: Install BLAS (windows)
      if: matrix.os == 'windows-latest'
      run: |
        nuget install openblas -ExcludeVersion 
        mv OpenBLAS/lib .
    - name: Set up Rust
      run: rustup default ${{ matrix.toolchain }} && rustup update ${{ matrix.toolchain }} --no-self-update && rustup component add clippy
    - name: Rust version
      run: rustc -Vv
    - name: Remote debug (windows)
      if: matrix.os == 'windows-latest'
      uses: mxschmitt/action-tmate@v3
    - name: Run tests - default features
      run: cargo test --verbose 
    - name: Clippy - default features
      run: cargo clippy --verbose
    - name: Docs - default features
      run: cargo rustdoc
